name: CI/CD for NestJS Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build --target production -t mindgpt-ai-hub:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag mindgpt-ai-hub:latest ${{ secrets.DOCKER_USERNAME }}/mindgpt-ai-hub:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mindgpt-ai-hub:latest

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.AWS_EC2_HOST }} # Your EC2 instance's public IP or hostname
          USER: ${{ secrets.AWS_EC2_USER }} # SSH user on your EC2 instance
          ENV: ${{ secrets.ENV }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/mindgpt-ai-hub:latest

            docker stop mindgpt-ai-hub || true
            docker rm mindgpt-ai-hub || true

            echo $ENV > ~/mindgpt/mindgpt-ai-hub/.env

            docker run -d --name mindgpt-ai-hub \
              --env-file ~/mindgpt/mindgpt-ai-hub/.env \
              -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/mindgpt-ai-hub:latest
          EOF
